### ISSUE TITLE
java.lang.ClassNotFoundException: flak.Flak

### ISSUE THREAD

**Issue by the-pavuk** [pcdv/flak#7]
Flak.createApp output ClassNotFoundException (im trying do redirect)

**Comment by pcdv** [comment]
Hi,

Do you have a stack trace? Which version are you using?

Maybe you forgot to add flak-backend-jdk to your classpath.

**Comment by the-pavuk** [comment]
im using 1.3.3 version 
flak-backend-jdk added
`[14:50:30 WARN]: [AutoWhitelist] Plugin AutoWhitelist v1.0-SNAPSHOT generated an exception while executing task 477
java.lang.NoClassDefFoundError: flak/Flak
        at ru.autowhitelist.autowhitelist.DonationAlerts.createApp(DonationAlerts.java:26) ~[?:?]
        at ru.autowhitelist.autowhitelist.CommandGet$1.run(CommandGet.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: flak.Flak
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Yatopia-"3770a43"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 8 more`

**Comment by pcdv** [comment]
I'm not sure. It looks like flak-api is not in your classpath. Is it the first time you try flak or did it work before?

If it used to work, can you try with version 1.2.0? I recently switched to Gradle 6.8.2 and there could be packaging issues. But I haven't had any problem with JDK8 or JDK15.

**Comment by the-pavuk** [comment]
yes, im using flak first time, but version 1.2.0 output same error

**Comment by pcdv** [comment]
In that case, the problem is not in Flak but in the way it is deployed in bukkit. 

I have no experience with bukkit, but if plugins are deployed as a single jar, then you need to create a "fat jar" including all its dependencies.

**Comment by the-pavuk** [comment]
thank you
